version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: rudakov19/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/media/

  frontend:
    image: rudakov19/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: rudakov19/foodgram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media/
